[phases.setup]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npx prisma migrate deploy && echo 'âœ… Migrations completed'", "echo 'ğŸš€ Starting seeding...'" , "npm run prisma:seed || echo 'âŒ Seeding failed with error'", "echo 'ğŸš€ Starting server...' && node dist/server.js"]
