[phases.setup]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npx prisma migrate deploy && echo '✅ Migrations completed'", "npx ts-node src/seed.ts && echo '✅ Seeding completed'", "node dist/server.js"]
