[phases.setup]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npx prisma migrate deploy && echo '✅ Migrations completed'", "npm run prisma:seed && echo '✅ Seeding completed'", "node dist/server.js"]
